### ISSUE TITLE
Collisions Not Working For Negative Positions

### ISSUE THREAD

**Issue by JAD3N** [fenomas/voxel-aabb-sweep#3]
I was just giving this a few tests and noticed that negative coordinates can cause the collision to stop working correctly. A slightly modified example should help:

```js
var sweep = require('voxel-aabb-sweep')
var getVoxel = function(x,y,z) { return y == 0 && x == 0 && z == 0 }
var box = { base: [-50,10,-50], max: [-20,20,-20], translate: function() {} }
var vector = [ 0, -10, 0 ]
var dist = sweep( getVoxel, box, vector, function() {
    return true
})

console.log(dist);
// this returns 20 when it should only return 9
```

**Comment by fenomas** [comment]
Hi, can you double-check that repro code? I get the output `10`, which looks correct - the `getVoxel` only returns true for `[0,0,0]`, and the AABB doesn't collide with that position.

**Comment by JAD3N** [comment]
Ah I just double checked as well, silly error! Thank you.
